// Scripts/productsData.js

const allProductsData = {
    // --- New Arrivals (5 items) ---
    "top-pink-ribbed": {
        id: "top-pink-ribbed",
        name: "Pink Ribbed Top",
        price: 500,
        originalPrice: null,
        img: "assets/images/top1.jpg",
        category: "Tops",
        isNewArrival: true, // This flag is crucial for the homepage
        tags: ["new arrival", "top", "ribbed", "casual"],
        gallery: [
            "assets/images/top1.jpg",
            "https://placehold.co/600x800/F8F8F8/333?text=Pink+Top+View+2",
            "https://placehold.co/600x800/F8F8F8/333?text=Pink+Top+Detail"
        ],
        description: "A chic and comfortable pink ribbed top, perfect for everyday wear or dressing up. Its soft, stretchy fabric provides a flattering fit.",
        availableSizes: ["XS", "S", "M", "L", "XL"],
        measurements: { "XS": { shoulder: "34", chest: "80", bust: "82", length: "55" }, "S": { shoulder: "36", chest: "84", bust: "86", length: "57" }, "M": { shoulder: "38", chest: "88", bust: "90", length: "59" }, "L": { shoulder: "40", chest: "92", bust: "94", length: "61" }, "XL": { shoulder: "42", chest: "96", bust: "98", length: "63" } },
        howToStyle: "Pair with high-waisted jeans and sneakers for a casual look, or tuck into a skirt with heels for an evening out. Layer with a blazer for a sophisticated touch. Ideal for both day and night events.",
        careInstructions: "Machine wash cold with like colors. Tumble dry low. Do not bleach. Iron on low heat if needed. Avoid harsh detergents to maintain color.",
        material: "95% Cotton, 5% Spandex",
        quantityAvailable: 10
    },
    "jeans-high-waisted": {
        id: "jeans-high-waisted",
        name: "High-Waisted Jeans",
        price: 1500,
        originalPrice: null,
        img: "assets/images/new_jeans.jpg", // Ensure this path is correct or create a placeholder
        category: "Trousers",
        isNewArrival: true,
        tags: ["new arrival", "jeans", "high-waisted", "denim"],
        gallery: ["assets/images/new_jeans.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Jeans+View+2"],
        description: "Classic high-waisted jeans offering a flattering silhouette and comfortable fit. A versatile staple for any wardrobe.",
        availableSizes: ["26", "28", "30", "32", "34"],
        measurements: { "26": { waist: "66", hips: "90", inseam: "75" }, "28": { waist: "71", hips: "95", inseam: "76" }, "30": { waist: "76", hips: "100", inseam: "77" } },
        howToStyle: "Pair with a tucked-in t-shirt or a flowy blouse. Dress up with heels or keep it casual with sneakers. Perfect for everyday wear.",
        careInstructions: "Machine wash cold inside out. Tumble dry low. Do not bleach. Iron on medium heat.",
        material: "100% Cotton Denim",
        quantityAvailable: 8
    },
    "bag-classic-tote": {
        id: "bag-classic-tote",
        name: "Classic Leather Tote",
        price: 3500,
        originalPrice: null,
        img: "assets/images/new_tote.jpg", // Ensure this path is correct or create a placeholder
        category: "Bags",
        isNewArrival: true,
        tags: ["new arrival", "bag", "leather", "tote", "accessory"],
        gallery: ["assets/images/new_tote.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Tote+Bag+View+2"],
        description: "A spacious and elegant leather tote bag, perfect for work or daily use. Features sturdy handles and multiple compartments.",
        availableSizes: ["One Size"],
        measurements: { "One Size": { width: "35", height: "30", depth: "12", handle_drop: "25" } },
        howToStyle: "Ideal for carrying all your essentials while maintaining a sophisticated look. Complements business attire or smart casual outfits.",
        careInstructions: "Wipe clean with a damp cloth. Use leather conditioner periodically. Store in a dust bag when not in use.",
        material: "Genuine Leather",
        quantityAvailable: 5
    },
    "dress-boho-maxi": {
        id: "dress-boho-maxi",
        name: "Boho Maxi Dress",
        price: 2200,
        originalPrice: null,
        img: "assets/images/new_maxidress.jpg", // Ensure this path is correct or create a placeholder
        category: "Dresses",
        isNewArrival: true,
        tags: ["new arrival", "dress", "maxi", "boho", "summer"],
        gallery: ["assets/images/new_maxidress.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Maxi+Dress+View+2"],
        description: "A flowing bohemian maxi dress, perfect for warm weather and relaxed days. Features a comfortable fit and vibrant print.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { bust: "90", length: "130" }, "M": { bust: "95", length: "132" }, "L": { bust: "100", length: "134" } },
        howToStyle: "Wear with sandals and a wide-brimmed hat for a beach-ready look. Layer with a denim jacket for cooler evenings.",
        careInstructions: "Machine wash cold, gentle cycle. Hang dry. Do not tumble dry. Iron on low heat.",
        material: "100% Rayon",
        quantityAvailable: 7
    },
    "belt-leather-braid": {
        id: "belt-leather-braid",
        name: "Braided Leather Belt",
        price: 800,
        originalPrice: null,
        img: "assets/images/new_belt.jpg", // Ensure this path is correct or create a placeholder
        category: "Belts",
        isNewArrival: true,
        tags: ["new arrival", "belt", "leather", "accessory"],
        gallery: ["assets/images/new_belt.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Belt+View+2"],
        description: "A stylish braided leather belt that adds a touch of rustic charm to any outfit. Adjustable for a perfect fit.",
        availableSizes: ["S/M", "M/L"],
        measurements: { "S/M": { length: "100", width: "3" }, "M/L": { length: "115", width: "3" } },
        howToStyle: "Cinch your waist over a dress or tunic. Pair with jeans or trousers to complete your look. Versatile for casual and smart-casual styles.",
        careInstructions: "Wipe clean with a soft, dry cloth. Use leather conditioner periodically. Do not submerge in water.",
        material: "Genuine Leather",
        quantityAvailable: 12
    },

    // --- Our Looks (5 items) ---
    "look-brunch-babe": {
        id: "look-brunch-babe",
        name: "Brunch Babe Look",
        price: 1200,
        originalPrice: null,
        img: "assets/images/styled-look1.jpg",
        category: "Looks", // Categorize as a 'Look'
        isLook: true, // This flag is crucial for the homepage
        tags: ["styled look", "brunch", "casual chic"],
        gallery: ["assets/images/styled-look1.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Brunch+Look+View+2"],
        description: "Effortlessly chic, this brunch babe look combines comfort with style. Perfect for a leisurely weekend outing.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { shoulder: "36", chest: "88", bust: "90", length: "90" }, "M": { shoulder: "38", chest: "92", bust: "94", length: "92" }, "L": { shoulder: "40", chest: "96", bust: "98", length: "94" } },
        howToStyle: "Accessorize with a wide-brimmed hat and sandals for a perfect brunch outfit. Can be dressed up with wedges or down with trainers.",
        careInstructions: "Hand wash cold. Do not bleach. Hang to dry. Iron on low heat.",
        material: "Cotton Blend",
        quantityAvailable: 7
    },
    "look-evening-glam": {
        id: "look-evening-glam",
        name: "Evening Glam Look",
        price: 4500,
        originalPrice: null,
        img: "assets/images/look_evening.jpg", // Ensure this path is correct or create a placeholder
        category: "Looks",
        isLook: true,
        tags: ["styled look", "evening", "glamorous", "party"],
        gallery: ["assets/images/look_evening.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Evening+Look+View+2"],
        description: "A stunning ensemble designed for those special evenings out. Exudes sophistication and allure.",
        availableSizes: ["XS", "S", "M", "L"],
        measurements: { "XS": { bust: "80", waist: "60", length: "150" }, "S": { bust: "84", waist: "64", length: "152" } },
        howToStyle: "Pair with statement jewelry and high heels. A clutch bag completes this glamorous look.",
        careInstructions: "Dry clean only.",
        material: "Silk Blend",
        quantityAvailable: 3
    },
    "look-casual-chic": {
        id: "look-casual-chic",
        name: "Casual Chic Look",
        price: 2800,
        originalPrice: null,
        img: "assets/images/look_casual.jpg", // Ensure this path is correct or create a placeholder
        category: "Looks",
        isLook: true,
        tags: ["styled look", "casual", "chic", "everyday"],
        gallery: ["assets/images/look_casual.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Casual+Look+View+2"],
        description: "Effortlessly stylish for your daily adventures. Combines comfort with a refined edge.",
        availableSizes: ["S", "M", "L", "XL"],
        measurements: { "S": { top_bust: "88", pants_waist: "68", pants_inseam: "70" } },
        howToStyle: "Team with clean white sneakers or ankle boots. A simple crossbody bag adds functionality.",
        careInstructions: "Refer to individual garment care labels.",
        material: "Cotton & Denim",
        quantityAvailable: 6
    },
    "look-office-pro": {
        id: "look-office-pro",
        name: "Office Pro Look",
        price: 3200,
        originalPrice: null,
        img: "assets/images/look_office.jpg", // Ensure this path is correct or create a placeholder
        category: "Looks",
        isLook: true,
        tags: ["styled look", "office", "professional", "workwear"],
        gallery: ["assets/images/look_office.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Office+Look+View+2"],
        description: "Sharp and sophisticated, this look is perfect for the modern professional. Command attention in the boardroom.",
        availableSizes: ["XS", "S", "M", "L"],
        measurements: { "S": { blazer_chest: "90", skirt_waist: "66", skirt_length: "60" } },
        howToStyle: "Complete with pointed heels and a structured handbag. A delicate necklace adds a touch of elegance.",
        careInstructions: "Dry clean recommended for blazer and skirt. Blouse: machine wash cold.",
        material: "Polyester Blend & Silk",
        quantityAvailable: 4
    },
    "look-weekend-vibe": {
        id: "look-weekend-vibe",
        name: "Weekend Vibe Look",
        price: 1900,
        originalPrice: null,
        img: "assets/images/look_weekend.jpg", // Ensure this path is correct or create a placeholder
        category: "Looks",
        isLook: true,
        tags: ["styled look", "weekend", "relaxed", "comfortable"],
        gallery: ["assets/images/look_weekend.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Weekend+Look+View+2"],
        description: "Embrace the relaxed spirit of the weekend with this comfortable yet stylish ensemble.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { hoodie_chest: "100", joggers_waist: "70", joggers_inseam: "72" } },
        howToStyle: "Perfect with your favorite trainers and a baseball cap for an ultimate casual appeal.",
        careInstructions: "Machine wash cold with like colors. Tumble dry low.",
        material: "Cotton Fleece & Jersey",
        quantityAvailable: 8
    },

    // --- Items on Sale (5 items) ---
    "skirt-sunset-sale": {
        id: "skirt-sunset-sale",
        name: "Sunset Skirt",
        originalPrice: 900,
        price: 600,
        img: "assets/images/sale1.jpg",
        category: "Skirts",
        isOnSale: true, // This flag is crucial for the homepage
        tags: ["sale", "skirt", "maxi", "flowy"],
        gallery: [
            "assets/images/sale1.jpg",
            "https://placehold.co/600x800/F8F8F8/333?text=Sunset+Skirt+View+2",
            "https://placehold.co/600x800/F8F8F8/333?text=Sunset+Skirt+Detail"
        ],
        description: "Flowy and vibrant, the Sunset Skirt is a perfect addition to your summer wardrobe. On sale now!",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { waist: "68", hips: "90", length: "75" }, "M": { waist: "72", hips: "94", length: "77" }, "L": { waist: "76", hips: "98", length: "79" } },
        howToStyle: "Pair with a simple white crop top and sandals for a beachy look. Can also be dressed up with a tucked-in blouse and espadrilles.",
        careInstructions: "Machine wash cold. Gentle cycle. Hang dry. Iron on low heat.",
        material: "100% Viscose",
        quantityAvailable: 15
    },
    "top-crop-sale": {
        id: "top-crop-sale",
        name: "Summer Crop Top",
        originalPrice: 750,
        price: 400,
        img: "assets/images/sale_croptop.jpg", // Ensure this path is correct or create a placeholder
        category: "Tops",
        isOnSale: true,
        tags: ["sale", "top", "crop", "summer"],
        gallery: ["assets/images/sale_croptop.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Crop+Top+View+2"],
        description: "A light and breezy crop top, perfect for hot summer days. Available at a special sale price!",
        availableSizes: ["XS", "S", "M"],
        measurements: { "XS": { bust: "78", length: "35" }, "S": { bust: "82", length: "37" }, "M": { bust: "86", length: "39" } },
        howToStyle: "Pair with high-waisted shorts, skirts, or jeans. Great for festivals or casual outings.",
        careInstructions: "Machine wash cold. Tumble dry low.",
        material: "Cotton Blend",
        quantityAvailable: 20
    },
    "trousers-wide-leg-sale": {
        id: "trousers-wide-leg-sale",
        name: "Wide Leg Trousers",
        originalPrice: 2000,
        price: 1200,
        img: "assets/images/sale_trousers.jpg", // Ensure this path is correct or create a placeholder
        category: "Trousers",
        isOnSale: true,
        tags: ["sale", "trousers", "wide leg", "comfortable"],
        gallery: ["assets/images/sale_trousers.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Trousers+View+2"],
        description: "Comfortable and stylish wide-leg trousers, now on sale! Perfect for a relaxed yet polished look.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { waist: "70", inseam: "78" }, "M": { waist: "75", inseam: "80" }, "L": { waist: "80", inseam: "82" } },
        howToStyle: "Pair with a fitted top and sandals or sneakers for a casual look. Can be dressed up with a blouse and wedges.",
        careInstructions: "Machine wash cold. Hang dry. Iron on low heat.",
        material: "Linen Blend",
        quantityAvailable: 10
    },
    "dress-denim-sale": {
        id: "dress-denim-sale",
        name: "Denim Shirtdress",
        originalPrice: 2800,
        price: 1800,
        img: "assets/images/sale_denimdress.jpg", // Ensure this path is correct or create a placeholder
        category: "Dresses",
        isOnSale: true,
        tags: ["sale", "dress", "denim", "shirtdress"],
        gallery: ["assets/images/sale_denimdress.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Denim+Dress+View+2"],
        description: "A versatile denim shirtdress, great for layering or wearing on its own. Grab it at a special price!",
        availableSizes: ["XS", "S", "M", "L"],
        measurements: { "XS": { bust: "85", length: "90" }, "S": { bust: "90", length: "92" }, "M": { bust: "95", length: "94" } },
        howToStyle: "Wear with sneakers for a casual vibe, or cinch with a belt and add ankle boots for a more styled look.",
        careInstructions: "Machine wash cold inside out. Tumble dry low. Iron on medium heat.",
        material: "100% Cotton Denim",
        quantityAvailable: 9
    },
    "bag-mini-crossbody-sale": {
        id: "bag-mini-crossbody-sale",
        name: "Mini Crossbody Bag",
        originalPrice: 1500,
        price: 900,
        img: "assets/images/sale_crossbody.jpg", // Ensure this path is correct or create a placeholder
        category: "Bags",
        isOnSale: true,
        tags: ["sale", "bag", "crossbody", "mini", "accessory"],
        gallery: ["assets/images/sale_crossbody.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Mini+Bag+View+2"],
        description: "A cute and compact mini crossbody bag, perfect for carrying your essentials. Now available at a discounted price!",
        availableSizes: ["One Size"],
        measurements: { "One Size": { width: "18", height: "12", depth: "6", strap_length: "110" } },
        howToStyle: "Ideal for light travel or evening outings. Adds a pop of style to any casual or semi-formal attire.",
        careInstructions: "Wipe clean with a damp cloth.",
        material: "Faux Leather",
        quantityAvailable: 18
    },

    // --- Other existing products (ensure these are still here if you need them elsewhere) ---
    "prod001": { // Example generic product to show existing structure being kept
        id: "prod001",
        name: "Example Ribbed Top (Generic)",
        price: 500,
        originalPrice: null,
        img: "assets/images/top1.jpg", // Example image
        category: "Tops",
        tags: ["top", "ribbed", "basic"],
        gallery: ["assets/images/top1.jpg", "https://placehold.co/600x800/F8F8F8/333?text=Generic+Top+View+2"],
        description: "A comfortable and versatile ribbed top for everyday wear.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { chest: "84", length: "57" } },
        howToStyle: "Easy to pair with jeans or skirts.",
        careInstructions: "Machine wash cold.",
        material: "Cotton",
        quantityAvailable: 10
    },
    "prod004": { // Example of a jacket (Generic)
        id: "prod004",
        name: "Vintage Denim Jacket (Generic)",
        price: 1500,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Vintage+Denim+Generic",
        category: "Jackets",
        tags: ["vintage", "denim", "jacket"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Vintage+Denim+Jacket+1", "https://placehold.co/600x800/F8F8F8/333?text=Vintage+Denim+Jacket+2"],
        description: "A timeless classic, this vintage denim jacket offers a relaxed fit and endless styling possibilities.",
        availableSizes: ["S", "M", "L", "XL"],
        measurements: { "S": { shoulder: "40", chest: "95", length: "60" } },
        howToStyle: "Layer over a floral dress or pair with a simple white tee and black jeans.",
        careInstructions: "Machine wash cold.",
        material: "100% Cotton Denim",
        quantityAvailable: 8
    },
    "prod005": { // Example Floral Midi Dress (Generic)
        id: "prod005",
        name: "Floral Midi Dress (Generic)",
        price: 1800,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Floral+Dress+Generic",
        category: "Dresses",
        tags: ["dress", "floral", "midi"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Floral+Midi+Dress+1", "https://placehold.co/600x800/F8F8F8/333?text=Floral+Midi+Dress+2"],
        description: "A beautiful floral midi dress, perfect for garden parties or a stylish day out.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { chest: "88", length: "110" } },
        howToStyle: "Pair with strappy sandals and a light cardigan.",
        careInstructions: "Machine wash cold, gentle cycle.",
        material: "100% Polyester",
        quantityAvailable: 6
    },
    "prod006": { // Example Leather Crossbody Bag (Generic)
        id: "prod006",
        name: "Leather Crossbody Bag (Generic)",
        price: 2500,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Leather+Bag+Generic",
        category: "Bags",
        tags: ["accessory", "bag", "leather"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Leather+Crossbody+Bag+1", "https://placehold.co/600x800/F8F8F8/333?text=Leather+Crossbody+Bag+2"],
        description: "A sleek and versatile leather crossbody bag, perfect for everyday essentials.",
        availableSizes: ["One Size"],
        measurements: { "One Size": { width: "20", height: "15", depth: "7" } },
        howToStyle: "Complements almost any outfit.",
        careInstructions: "Wipe clean with a damp cloth.",
        material: "Genuine Leather",
        quantityAvailable: 4
    },
    "top001": { // Example Silk Cami Top (Generic)
        id: "top001",
        name: "Silk Cami Top (Generic)",
        price: 750,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Silk+Cami+Generic",
        category: "Tops",
        tags: ["top", "cami", "silk"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Silk+Cami+1", "https://placehold.co/600x800/F8F8F8/333?text=Silk+Cami+2"],
        description: "Luxurious and lightweight, this silk cami top is perfect for layering.",
        availableSizes: ["XS", "S", "M", "L"],
        measurements: { "XS": { bust: "80", length: "45" } },
        howToStyle: "Layer under a blazer or wear on its own.",
        careInstructions: "Hand wash cold.",
        material: "100% Silk",
        quantityAvailable: 9
    },
    "top002": { // Example Embroidered Blouse (Generic)
        id: "top002",
        name: "Embroidered Blouse (Generic)",
        price: 900,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Embroidered+Blouse+Generic",
        category: "Tops",
        tags: ["top", "blouse", "embroidered"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Embroidered+Blouse+1", "https://placehold.co/600x800/F8F8F8/333?text=Embroidered+Blouse+2"],
        description: "A beautiful blouse featuring delicate embroidery, perfect for adding a touch of bohemian elegance.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { chest: "88", length: "60" } },
        howToStyle: "Pair with dark wash jeans or tuck into a high-waisted skirt.",
        careInstructions: "Hand wash cold.",
        material: "Cotton, Viscose",
        quantityAvailable: 12
    },
    "skirt001": { // Example Pleated Maxi Skirt (Generic)
        id: "skirt001",
        name: "Pleated Maxi Skirt (Generic)",
        price: 1100,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Maxi+Skirt+Generic",
        category: "Skirts",
        tags: ["skirt", "maxi", "pleated"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Pleated+Maxi+Skirt+1", "https://placehold.co/600x800/F8F8F8/333?text=Pleated+Maxi+Skirt+2"],
        description: "An elegant pleated maxi skirt that drapes beautifully. Perfect for a sophisticated and comfortable look.",
        availableSizes: ["S", "M", "L", "XL"],
        measurements: { "S": { waist: "65", length: "95" } },
        howToStyle: "Pair with a fitted top or a tucked-in blouse.",
        careInstructions: "Machine wash cold.",
        material: "100% Polyester",
        quantityAvailable: 8
    },
    "dress001": { // Example Boho Sundress (Generic)
        id: "dress001",
        name: "Boho Sundress (Generic)",
        price: 1600,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Sundress+Generic",
        category: "Dresses",
        tags: ["dress", "boho", "sundress"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Boho+Sundress+1", "https://placehold.co/600x800/F8F8F8/333?text=Boho+Sundress+2"],
        description: "A light and airy bohemian sundress, perfect for warm weather and relaxed vibes.",
        availableSizes: ["S", "M", "L"],
        measurements: { "S": { bust: "90", length: "100" } },
        howToStyle: "Wear with sandals and a wide-brimmed hat.",
        careInstructions: "Machine wash cold, delicate cycle.",
        material: "Cotton, Rayon",
        quantityAvailable: 10
    },
    "trousers001": { // Example High-Waist Trousers (Generic)
        id: "trousers001",
        name: "High-Waist Trousers (Generic)",
        price: 1300,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Trousers+Generic",
        category: "Trousers",
        tags: ["trousers", "high-waist", "pants"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=High-Waist+Trousers+1", "https://placehold.co/600x800/F8F8F8/333?text=High-Waist+Trousers+2"],
        description: "Stylish high-waist trousers that offer a flattering fit and comfortable wear.",
        availableSizes: ["XS", "S", "M", "L", "XL"],
        measurements: { "XS": { waist: "64", inseam: "70" } },
        howToStyle: "Pair with a tucked-in blouse and heels.",
        careInstructions: "Machine wash cold.",
        material: "Polyester, Spandex",
        quantityAvailable: 14
    },
    "bag001": { // Example Vintage Tote Bag (Generic)
        id: "bag001",
        name: "Vintage Tote Bag (Generic)",
        price: 1900,
        originalPrice: null,
        img: "https://placehold.co/300x300/F8F8F8/333?text=Tote+Bag+Generic",
        category: "Bags",
        tags: ["bag", "tote", "vintage"],
        gallery: ["https://placehold.co/600x800/F8F8F8/333?text=Vintage+Tote+Bag+1", "https://placehold.co/600x800/F8F8F8/333?text=Vintage+Tote+Bag+2"],
        description: "A spacious vintage tote bag, ideal for daily use or weekend getaways.",
        availableSizes: ["One Size"],
        measurements: { "One Size": { width: "35", height: "30", depth: "12" } },
        howToStyle: "Perfect for carrying essentials for work, school, or errands.",
        careInstructions: "Wipe clean with a damp cloth.",
        material: "Canvas with Faux Leather Trim",
        quantityAvailable: 7
    }
};

